### ISSUE TITLE
Erro no cadastro de produtos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-horus-erp#15]
@wisley7l bom dia!

Abrindo isso aqui, só pra saber mesmo e se tiver tratado diferente em outro lugar, pra ajustar.

Produto deve ter sempre price, que é o preço de venda. Caso não tenha, os pedidos não são finalizados (vai barrar no backend). O base_price é pra balizar desconto, no código de importação do produto, em nenhum momento trazia o price pro produto. 

Eu imaginei que eles devem fazer essa atualização, porque tem vários produtos com price e eles fazem a leitura na api para atualização desses preços com n8n, **se houver desconto**. Então, **se não houver**, eles não atualizam e esses produtos ficam sem possibilidade de compra

Quando vai enviar o pedido, bate sempre final_price, que é condição com algum desconto ou price e nunca o base_price. Isso estava gerando alguns erros em cálculo de frete, app de descontos, por exemplo, que é necessário ter o price.

**Comment by wisley7l** [comment]
@matheusgnreis, muito obrigado, vi aqui a correção.
Usei o base_price pois foi um pedido do cliente, com a finalizade de cadastrar dos descontos apenas, não me recordava que gerava outros problemas. 
Mas no  ultimo commit aqui fiz um outro ajuste que acredito que funcione melhor, pq quando houver atualização de preço no ERP vai verificar se o produto tem o price, se tive não tive vai adiciona-lo junto com a atualização do base_price. 
E na importação de poduto novo, so coloquei junto o que você já havia corrigido que é cadastrar o produto com o base_price e price.
